openapi: "3.0.1"
info:
  title: "ListAnnouncements API"
  description: "Api created using cloudformation"
  version: "2021-02-18T09:51:18Z"
servers:
- url: "https://ge2dc15vna.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/develop"
paths:
  /announcements:
    get:
      parameters:
      - name: "pagination_token"
        in: "query"
        schema:
          type: "string"
      responses:
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseModel"
        "500":
          description: "500 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseModel"
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponseModel"
components:
  schemas:
    ErrorResponseModel:
      title: "ErrorResponseModel"
      required:
      - "message"
      - "status"
      type: "object"
      properties:
        message:
          type: "string"
        status:
          type: "string"
      additionalProperties: false
    SuccessResponseModel:
      title: "SuccessResponseModel"
      required:
      - "message"
      - "status"
      type: "object"
      properties:
        pagination_token:
          type: "string"
        message:
          type: "string"
        announcements:
          type: "array"
          items:
            required:
            - "date"
            - "title"
            type: "object"
            properties:
              date:
                type: "string"
              title:
                type: "string"
        status:
          type: "string"
      additionalProperties: false
