AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        S3Bucket: "sidharthramesh"
        S3Key: "PutAnnouncement.zip"
      Description: "lambda function created using cloudformation"
      FunctionName: "sample_lambda_function_cloud_formation"
      Handler: "PutAnnouncement.lambda_handler"
      Role: "arn:aws:iam::010381976707:role/lambda-role-for-sqs-dynamodb-ec2"
      Runtime: "python3.6"
      Tags: 
        -
          Key: "Name"
          Value: "Sample lambda function"
      Timeout: 3