openapi: "3.0.1"
info:
  title: "PutAnnouncement API"
  description: "Api created using cloudformation"
  version: "2021-02-11T08:40:54Z"
servers:
- url: "https://msgfls6a57.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/develop"
paths:
  /announcement:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutAnnouncementModel"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MethodResponseModel"
components:
  schemas:
    MethodResponseModel:
      title: "MethodResponseModel"
      type: "object"
      properties:
        message:
          type: "string"
        status:
          type: "string"
      additionalProperties: false
    PutAnnouncementModel:
      title: "PutAnnouncementModel"
      required:
      - "date"
      - "title"
      type: "object"
      properties:
        date:
          minLength: 1
          type: "string"
        title:
          minLength: 1
          type: "string"
      additionalProperties: false
