AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TableName:
    Type: String
Resources:
  AnnouncementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "AnnouncementId"
          AttributeType: "S"
      BillingMode: PROVISIONED
      KeySchema: 
        - 
          AttributeName: "AnnouncementId"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref TableName
      Tags: 
        -
          Key: "Name"
          Value: !Ref TableName
Outputs:
  TableName:
    Value:
      Ref: AnnouncementTable