AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ErrorReportingLambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        S3Bucket: "sidharthramesh"
        S3Key: "ErrorReporting.zip"
      Description: "Error reporting lambda function - sends out email alerts to users through SNS"
      FunctionName: "error_reporting"
      Handler: "ErrorReporting.lambda_handler"
      Role: !GetAtt LambdaFunctionIAMRole.Arn
      Runtime: "python3.6"
      Timeout: 3
      Environment:
        Variables:
          snsARN: !Ref ErrorReportingSnsTopic

  LambdaFunctionIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: LoggingAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents" 
                Resource: '*'
              - Effect: Allow
                Action: "SNS:Publish"
                Resource: !Ref ErrorReportingSnsTopic
      RoleName: ErrorParsingLambdaRole

  ErrorReportingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref ErrorReportingLambdaFunction]]
      RetentionInDays: 7

  ErrorReportingSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Error Reporting SNS Topic"
      TopicName: "error_reporting_topic"
  
  SnsTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: "sidharthr44@gmail.com"
      Protocol: "email"
      TopicArn: !Ref ErrorReportingSnsTopic
  
Outputs:
  ErrorReportingLambdaFunctionArn:
    Value: !GetAtt ErrorReportingLambdaFunction.Arn
  ErrorReportingLambdaFunctionName:
    Value: !Ref ErrorReportingLambdaFunction
