AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  LambdaFunctionName:
    Type: String
  LambdaFunctionArn:
    Type: String
Resources:
  ListAnnouncementsAPI:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "ListAnnouncements API"
      Description: "Api created using cloudformation"

  AnnouncementsResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref ListAnnouncementsAPI
      ParentId: !GetAtt ListAnnouncementsAPI.RootResourceId
      PathPart: announcements
    
  AnnouncementsGetMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: GET
      ResourceId: !Ref AnnouncementsResource
      RestApiId: !Ref ListAnnouncementsAPI
      AuthorizationType: NONE
      RequestParameters:
        method.request.querystring.pagination_token: false
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Join [ "", [ "arn:aws:apigateway:", !Ref "AWS::Region", ":lambda:path/2015-03-31/functions/", !Ref LambdaFunctionArn, "/invocations" ] ]
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          "application/json": "{ \"pagination_token\" : \"$input.params('pagination_token')\" }"
        IntegrationResponses:
          - ResponseTemplates:
              "application/json": "#set($inputRoot = $input.path('$')) { \"message\" : \"$inputRoot.message\", \"status\" : \"$inputRoot.statusCode\", \"announcements\" : [  #foreach($elem in $inputRoot.items){\"title\" : \"$elem.title\", \"date\" : \"$elem.date\", \"description\" : \"$elem.description\" }  #if($foreach.hasNext),#end #end ] #if ($inputRoot.pagination_token != \"\") ,\"pagination_token\" : \"$inputRoot.pagination_token\" #end }"
            StatusCode: 200
          - ResponseTemplates:
              "application/json": "#set($inputRoot = $input.path('$')) { \"message\" : \"$inputRoot.errorMessage\", \"status\" : 400 }"
            SelectionPattern: ".*Invalid pagination_token.*"
            StatusCode: 400
          - ResponseTemplates:
              "application/json": "#set($inputRoot = $input.path('$')) { \"message\" : \"$inputRoot.errorMessage\", \"status\" : 500 }"
            SelectionPattern: ".*Internal.*"
            StatusCode: 500
      MethodResponses:
        - 
          ResponseModels:
            "application/json": !Ref SuccessResponseModel
          StatusCode: 200
        -
          ResponseModels:
            "application/json": !Ref ErrorResponseModel
          StatusCode: 400
        -
          ResponseModels:
            "application/json": !Ref ErrorResponseModel
          StatusCode: 500

  SuccessResponseModel:
    Type: "AWS::ApiGateway::Model"
    Properties:
      ContentType: "application/json"
      Name: "SuccessResponseModel"
      RestApiId: !Ref ListAnnouncementsAPI
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        title: SuccessResponseModel
        type: object
        additionalProperties: false
        properties:
          status:
            type: string
          message:
            type: string
          announcements:
            type: array
            items:
              type: object
              properties:
                title:
                  type: string
                date:
                  type: string
                description:
                  type: string
              required: [title, date, description]
          pagination_token:
            type: string
        required: [status, message]

  ErrorResponseModel:
    Type: "AWS::ApiGateway::Model"
    Properties:
      ContentType: "application/json"
      Name: "ErrorResponseModel"
      RestApiId: !Ref ListAnnouncementsAPI
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        title: ErrorResponseModel
        type: object
        additionalProperties: false
        properties:
          status:
            type: string
          message:
            type: string
        required: [status, message]

  ListAnnouncementsApiStage:
    Type: "AWS::ApiGateway::Stage"
    Properties:
      DeploymentId: !Ref ListAnnouncementsAPIDeployment
      Description: "Develop stage created in CloudFormation"
      RestApiId: !Ref ListAnnouncementsAPI
      StageName: "develop"
  
  ListAnnouncementsAPIDeployment:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      Description: "ListAnnouncementsAPI Deployment"
      RestApiId: !Ref ListAnnouncementsAPI
    DependsOn: AnnouncementsGetMethod

  ApiGatewayLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:invokeFunction
      FunctionName: !Ref LambdaFunctionName
      Principal: apigateway.amazonaws.com

Outputs:
  ApiUrl:
    Description: "The endpoint URL exposed by API Gateway"
    Value: !Sub "https://${ListAnnouncementsAPI}.execute-api.${AWS::Region}.amazonaws.com/${ListAnnouncementsApiStage}"