AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AnnouncementsTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sidharthramesh.s3-eu-west-1.amazonaws.com/db.cfn.yaml"
  
  PutAnnouncementLambdaFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sidharthramesh.s3-eu-west-1.amazonaws.com/lambda_function.cfn.yaml"
      Parameters:
        FunctionName: "put-announcements-function"
        FunctionHandler: "PutAnnouncement.lambda_handler"
        FunctionRoleArn: "arn:aws:iam::010381976707:role/lambda-role-for-sqs-dynamodb-ec2"
        S3Bucket: "sidharthramesh"
        S3Key: "PutAnnouncement.zip"

  PutAnnouncementApi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sidharthramesh.s3-eu-west-1.amazonaws.com/api.cfn.yaml"
      Parameters:
        LambdaFunctionName: 
          Fn::GetAtt:
            - PutAnnouncementLambdaFunction
            - Outputs.FunctionName
        LambdaFunctionArn:
          Fn::GetAtt:
            - PutAnnouncementLambdaFunction
            - Outputs.FunctionArn
    