AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AnnouncementsTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sidharthramesh.s3-eu-west-1.amazonaws.com/db.cfn.yaml"
  
  PutAnnouncementLambdaFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sidharthramesh.s3-eu-west-1.amazonaws.com/common/lambda_function.cfn.yaml"
      Parameters:
        FunctionName: "put-announcements-function"
        FunctionHandler: "PutAnnouncement.lambda_handler"
        FunctionRoleArn: "arn:aws:iam::010381976707:role/lambda-role-for-sqs-dynamodb-ec2"
        S3Bucket: "sidharthramesh"
        S3Key: "PutAnnouncement.zip"

  PutAnnouncementApi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sidharthramesh.s3-eu-west-1.amazonaws.com/api.cfn.yaml"
      Parameters:
        LambdaFunctionName: 
          Fn::GetAtt:
            - PutAnnouncementLambdaFunction
            - Outputs.FunctionName
        LambdaFunctionArn:
          Fn::GetAtt:
            - PutAnnouncementLambdaFunction
            - Outputs.FunctionArn
    
  ListAnnouncementsLambdaFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sidharthramesh.s3-eu-west-1.amazonaws.com/common/lambda_function.cfn.yaml"
      Parameters:
        FunctionName: "list_announcements"
        FunctionHandler: "ListAnnouncements.lambda_handler"
        FunctionRoleArn: "arn:aws:iam::010381976707:role/lambda-role-for-sqs-dynamodb-ec2"
        S3Bucket: "sidharthramesh"
        S3Key: "ListAnnouncements.zip"
    
  ListAnnouncementsAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://sidharthramesh.s3-eu-west-1.amazonaws.com/list_announcements_api.cfn.yaml"
      Parameters:
        LambdaFunctionName: 
          Fn::GetAtt:
            - ListAnnouncementsLambdaFunction
            - Outputs.FunctionName
        LambdaFunctionArn:
          Fn::GetAtt:
            - ListAnnouncementsLambdaFunction
            - Outputs.FunctionArn

Outputs:
  PutAnnouncementEndpointURL:
    Description: "Endpoint URL for put-announcement API exposed by API Gateway"
    Value: 
      Fn::GetAtt:
        - PutAnnouncementApi
        - Outputs.ApiUrl

  ListAnnouncementsEndpointURL:
    Description: "Endpoint URL for list-announcements API exposed by API Gateway"
    Value: 
      Fn::GetAtt:
        - ListAnnouncementsAPI
        - Outputs.ApiUrl